### ISSUE TITLE
No output in Modx 3.0.5

### ISSUE THREAD

**Issue by valokammi** [qodo/TableOfContentsX#2]
Testing this extra in my testing server (Laragon,PHP 8.0, windows) with ModX 3.0.5. Install Ok!
I put [[TableOfContentsX=`toc`]] in to page template.
TableOfContentsX snippet is in its place but no output at all.
In error log is this:
[2024-09-24 18:36:27] (ERROR @ C:\laragon\www\onepage\core\src\Revolution\modParser.php : 512) Could not find snippet with name TableOfContentsX=`toc`.
Am I doing something wrong or is this a bug?

**Comment by qodo** [comment]
@valokammi Can you check that you are adding to your page correctly?

This needs to have backticks around `toc` like documented here
https://www.qodo.co.uk/blog/tableofcontentsx-a-new-modx-extra-for-creating-a-table-of-contents/

```
[[*content:TableOfContentsX=`toc`]]
[[*content:TableOfContentsX=`content`]]
```

**Comment by valokammi** [comment]
Actually backticks are there but this system thinks it is "code" and they not show.
Now snippets output too much. Started new issue.
